### ISSUE TITLE
Make 'account' for the slurm_header an input option

### ISSUE THREAD

**Issue by milenaveneziani** [E3SM-Project/zppy#157] opened 2021-10-15 22:53 UTC
It would be nice to be able to choose the `account` name in the `default` section of the config file (basically removing the hard-coded `e3sm` value in `zppy/templates/slurm_header.sh`).

**Comment by xylar** [comment] 2021-10-16 00:27
@forsyth2, I'm happy to implement this sometime if you don't get a chance.  Seems pretty simple.

**Comment by chengzhuzhang** [comment] 2024-12-09 22:02
I think this has been implemented, could you confirm? @forsyth2

**Comment by forsyth2** [comment] 2024-12-09 23:25
Yes, #244 closed #238, which is a duplicate of this issue.

**Closed by forsyth2** 2024-12-09 23:25 UTC
Labels: priority: low
