### ISSUE TITLE
[Enhancement]: Separate `e3sm_to_cmip` task from `ts`

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/zppy#649] opened 2024-12-06 19:00 UTC
### What happened?

@forsyth2 I think we agreed on to make `e3sm_to_cmip` as a separate task, but not sure if there is an issue for this. Currently, we use a `ts_fmt` parameter to flag if additional cmip formatted time-series is needed in case of downstream processes, such as ilamb or (ongoing PMP integration).

 However, in current implementation, if there is an error from e3sm_to_cmip conversion, any downstream analyses (e3sm_diags, global-time-series) that depends on `ts` (ncclimo generated time-series files) would not run. It would be cleaner to have the e3sm_to_cmip task a separate task before the PMP integration. Note that, if we need to include e3sm_to_cmip task for MPAS files, we may need a new task because for MPAS output, e3sm_to_cmip depends on native history files at this point.  

### What machine were you running on?

NA

### Environment

NA

### What command did you run?

```bash
NA
```

### Copy your cfg file

```bash
NA
```

**Comment by forsyth2** [comment] 2024-12-06 19:13
> not sure if there is an issue for this

Yes, this is a duplicate of #467.

**Comment by chengzhuzhang** [comment] 2024-12-06 19:15
Thank you, it's from more than one year ago. yeah, we definitely need it to be prioritized.

**Comment by forsyth2** [comment] 2024-12-07 00:19
@chengzhuzhang I'm glad to see this being prioritized. I got started a preliminary implementation at #650, but it still needs substantial work. Importantly, we're looking at a major version increase (`zppy v3.0.0`) because the `e3sm_to_cmip` capabilities will now be implemented via an entirely different section in the `cfg` files.

**Closed** 2024-12-18 20:01 UTC
Labels: semver: new feature
